### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#209]
1. We would like to create a basic accordion component like the following template:
```tsx
<Accordion titleClassName="" detailsClassName="" multipleOpen={false|true} expanded='panel2' expandIcon={genericComponent}>
  <AccordionItem title="panel1" className="" accordionProps={} >
    <AccordionTitle className="" titleProps={} />
    <AccordionDetails className={} detailsProps={} />
  </AccordionItem>
  <AccordionItem>
    <AccordionTitle/>
    <AccordionDetails/>
  </AccordionItem>
</Accordion>
```
 **Please make sure that the component works as well without JS enabled**
Another example is the following: https://design-system.service.gov.uk/components/accordion/
**Important**: please use **release/1.0.0** as base branch

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/accordion'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/544
