### ISSUE TITLE
Unable to run 'yarn lint' on Windows machine

### ISSUE THREAD

**Issue by CanerCap** [Capgemini/dcx-react-library#225]
**Describe the bug**
When trying to run 'yarn lint' or 'yarn lint:fix' an error occurs. The error is related to the 'developit' config and babel but only seems to occur on a Windows machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/24546769/134137764-22977bac-5408-48ce-9e40-bfb5b7fced1f.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by daniele-zurico** [comment]
it should work as expected now.... closing it please reopen if still not work
