### ISSUE TITLE
Autocomplete is not non-js compliant

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#276]
The [Autocomplete](https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-form-autocomplete-documentation--page) component doesn't work if javascript is disabled.

To make it work when js is disabled we need to turn the component into a select.

To disable Javascript on your chrome browser please refer to the [following guide](https://developer.chrome.com/docs/devtools/javascript/disable/)

Please refer to [accessible-autocomplete](https://github.com/alphagov/accessible-autocomplete) for a working example

It also doesn't allow to:
- to specify a class for the container
- to specify a label 
- to specify a label class Name
-  to pass an id to the input or select element(in case of progressive enhancement)
- to display an error message in three different positions (BEFORE_LABEL, BOTTOM, AFTER_LABEL and AFTER_HINT)
- error message text
- error className
-  error id

**Please create your branch from release/0.5**
```bash
git checkout release/0.5
git pull
git checkout -b 'feature/autocmplete-nonJs'
```

**Comment by daniele-zurico** [comment]
closed with #307
