### ISSUE TITLE
Tabs is not non-js compliant

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#283]
[Tabs](https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-tabs-documentation--page) is not non-js compliant, with js turn off contents of all tabs do not display

To disable Javascript on your chrome browser please refer to the [following guide](https://developer.chrome.com/docs/devtools/javascript/disable/)

**Please create your branch from release/0.7**
```bash
git checkout release/0.7
git pull
git checkout -b 'feature/tab-nonJs'
```

Describe the solution you'd like
tabs should be able to work without javascript enabled current it doesn't

**Comment by cg-julian-taylor** [comment]
I've been given the recommendation to look at the tabs behaviour in [GDS component library](https://design-system.service.gov.uk/components/tabs/). The non JS approach they use is to list all the tabs as links and then put all the tab contents underneath each other.

I will code the layout to match this approach as long as that is ok with everyone else.
