### ISSUE TITLE
Review dependabot alerts

### ISSUE THREAD

**Issue by tsphethean** [Capgemini/dcx-react-library#287]
There are a number of dependabot alerts indicating security vulnerabilities in dependent packages for this repo.

Full list is at https://github.com/Capgemini/dcx-react-library/security/dependabot and includes 8 critical items at the time of writing. 

Please review the alerts and update dependencies wherever possible.

**Comment by Ibabalola** [comment]
thanks @tsphethean - within the current release we have addressed all of the 9 *critical* items and other items where possible, so I will close this for now with a keen eye on the dependabot scan after this has been merged into our main branch.
