### ISSUE TITLE
Autocomplete - Add option 'required'

### ISSUE THREAD

**Issue by dchatzinaki** [Capgemini/dcx-react-library#291]
In the [autocomplete component](https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-form-autocomplete-documentation--page) we need to provide the ability to have an extra attribute called `required`.
By default set to false and the user can change to true.
The input field will be rendered with a required attribute, see W3C required attribute definition.
```tsx
required?: boolean
```
**Please create your branch from release/0.5**
```bash
git checkout release/0.5
git pull
git checkout -b 'feature/autocomplete-required'
```

**Comment by daniele-zurico** [comment]
#308 closed the following ticket
