### ISSUE TITLE
Autocomplete  -  Add option to show all values

### ISSUE THREAD

**Issue by dchatzinaki** [Capgemini/dcx-react-library#292]
In the [autocomplete component](https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-form-autocomplete-documentation--page) we need to provide the ability to show all the values when the user clicks the input.
We'll create an extra optional attribute called `showAllValues` by default set to false and the user can change it to true.
This is similar to a default dropdown, so the autocomplete is rendered with a dropdown arrow to convey this behavior.
```tsx
showAllValues?: boolean
```
For a working example please refer to the [following component](https://github.com/alphagov/accessible-autocomplete) and [demo](https://alphagov.github.io/accessible-autocomplete/examples/)

**Please remember to provide an example in the storybook**
**Please remember to provide an example in the example folder**

**Please create your branch from release/1.0.0**

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/autocomplete-showAll'
```

**Comment by daniele-zurico** [comment]
we closing for now this ticket as not needed. The main point raised was that an autocomplete is not a dropdown list and this functionality is closer to a ddl.
Let's see if in the future this functionality is requested
