### ISSUE TITLE
FormInput - add aria-required option

### ISSUE THREAD

**Issue by dchatzinaki** [Capgemini/dcx-react-library#293]
**Description**
In the [FormInput component](https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-form-input-documentation--page) add the "aria-required" attribute.
By default, the "aria-required" attribute will be **false** but we will provide the user the ability to pass a parameter to make it true.

```jsx
ariaAttribute?: boolean;
```
**Please create your branch from release/0.5**
```bash
git checkout release/0.5
git pull
git checkout -b 'feature/formInput-aria'
```

**Comment by daniele-zurico** [comment]
closed with PR #333
