### ISSUE TITLE
Conditional fields in checkbox only works when JS enabled

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#309]
**Describe the bug**
Conditional input in checkbox here: https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/story/dcxlibrary-form-checkbox--conditional seems to only work only when JS is enabled. We need this component to display the conditional field when there is no Javascript in the browser (as shown here https://design-system.service.gov.uk/components/checkboxes/conditional-reveal/index.html), and if there is Javascript then it can be conditional.

**To Reproduce**
1. Use the checkbox component with a conditional input
2. In the browser, turn on/off JS to observe above issue

**Expected behavior**
We need this component to display the conditional fields when there is no Javascript in the browser (as shown here https://design-system.service.gov.uk/components/checkboxes/conditional-reveal/index.html), and if there is Javascript then it can be conditional.

**Screenshots**
See links above

**Desktop (please complete the following information):**
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**
We are working on a project that requires the app to be functional without Javascript

Please create your branch from release/0.5
```sh
git checkout release/0.5
git pull
git checkout -b 'feature/conditional-checkbox'
```

**Comment by daniele-zurico** [comment]
closed by #325
