### ISSUE TITLE
Don't print/render the error span if text value in the error prop is null/undefined/falsy

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#315]
**Describe the bug**
See screenshot where an empty is span is printed/rendered for FormSelect because the error.text prop is empty/falsy. It would be nice to do an additional check if it's text value in the error prop is empty/falsy not to print/render the error span element in the HTML. This probably applies to other components in this library.

**To Reproduce**

1. Use the FormSelect in a React project and observe the HTML that gets rendered when you add an error prop but the text for the error is empty/falsy like this

```
error={{
 text: myErrorText, //sometime this is empty/flasy
}}
```

**Expected behavior**
If the error.text is empty or falsy, not to render or print the error span

**Screenshots**
![PixelSnap 2022-07-13 at 15 18 51](https://user-images.githubusercontent.com/5403134/178757393-b699b5e5-648f-44db-88c2-9d0f60b0b2f6.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by daniele-zurico** [comment]
closed by #317
