### ISSUE TITLE
Revise how props are names in Autocomplete for consistency

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#319]
**Is your feature request related to a problem? Please describe.**
The Autocomplete props could be organised a bit better. At the moment the props fall into the falling categories
- Individual props directly passed to the component
- Props passed under a prop called inputProps
- Props passed under a prop called props

Example usage:
```
<Autocomplete
              containerClassName={classNames("govuk-form-group govuk-!-width-two-thirds ", {
                "govuk-form-group--error": errors?.exportDestination,
              })}
              errorPosition={AutoCompleteErrorPosition.AFTER_HINT}
              errorMessageText={errors?.exportDestination?.message}
              errorMessageClassName="govuk-error-message"
              id="exportDestination"
              defaultValue={formData.exportedTo === "" ? "" : exportLocation?.exportedTo?.officialCountryName || ""}
              labelText={t("commonWhatExportDestinationSelectTheDestinationCountry")}
              labelClassName="govuk-label"
              hintText={t("commonWhatExportDestinationHintSelectTheDestinationCountry")}
              hintClass="govuk-hint"
              props={{
                selectClassName: classNames("govuk-select", {
                  "govuk-select--error": errors?.exportDestination,
                }),
                staticErrorMessage: "static error message",
                name: "exportedTo",
                preselect: formData.exportedTo === "" ? "" : exportLocation?.exportedTo?.officialCountryName || "",
              }}
              resultUlClass="autocomplete__menu"
              resultlLiClass="autocomplete__option"
              inputProps={{
                className: classNames("govuk-input", {
                  "govuk-input--error": errors?.exportDestination,
                }),
              }}
              options={["", ...countries.map((c) => c.officialCountryName)]}
            />
```

**Describe the solution you'd like**
Anything that's not specific to the input or select elements of the Autocomplete, I suggest add to root level directly to the component, for examples options, id, name, containerClassName, etc.

Anything specific to the select element is added to newly created selectProps prop, so anything like select class, id, name for the select itself.

Anything specific to the input element is added to the inputProps prop, so anything like input class, id, name for the input itself.

I suggest we remove the prop called props as a whole.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by daniele-zurico** [comment]
Closed by #326
