### ISSUE TITLE
High and critical npm audit issues introduced from this library into our app

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#321]
**Describe the bug**
We are using this library in our app, however, when we run `npm audit`, there are a number of high and critical issues that are present directly as a result of using this library. Could you look into fixing these please as it impacts on us, due to security considerations.

**To Reproduce**
1. Run `npm audit` in your library
2. Note the issues in the generated report

**Expected behavior**
No npm issues (or at least nothing under critical and high)

**Screenshots**
Example of critical issue
![PixelSnap 2022-07-20 at 10 55 37](https://user-images.githubusercontent.com/5403134/179958354-0e059de7-eb34-445b-8eb8-c11c1ac0051d.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by daniele-zurico** [comment]
Closed by #324
