### ISSUE TITLE
Conditional checkbox: Allow developer to specify position of conditional via an additional prop

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#329]
Hello,
Regarding https://main--6069a6f47f4b9f002171f8e1.chromatic.com/?path=/docs/dcxlibrary-form-checkbox-styled--conditional-input

As a developer, I would like to be able to override the default position of the conditional input (which is by default nested within checkbox item). I suggest introduction of a prop called `conditionalPosition` which if not set, does nothing, but if set to "sibling" renders the conditional inout as a sibling of the checkbox item.

I appreciate the I can probably add in styles to overrider the look-and-feel but it would make the consumption of the library much easier if we are able to control the rendering position, as the stylesheet which the client is providing are expecting the html to be in a certain structure and aren't expected to override anything.

I have attached screenshot how the 2 options in the html look like

**Is your feature request related to a problem? Please describe.**
Our client is a government department and have their own stylesheets, which something expect the html to be structure in a certain way. See here for more information on the conditional checkboxes. https://design-system.service.gov.uk/components/checkboxes/

**Describe the solution you'd like**
An additional prop called something like position, under the conditional prop that accepts the value "sibling" which if true, renders the conditional input as a sibling after the checkbox item div.

![PixelSnap 2022-07-22 at 17 56 03](https://user-images.githubusercontent.com/5403134/180489634-7aae88ab-5fe5-4694-8f31-ee1961d38fb7.png)

```
git checkout release/0.5
git pull
git checkout -b 'feature/form-check-position'
```

**Comment by daniele-zurico** [comment]
closed by #339
