### ISSUE TITLE
Autocomplete: allow developer to prompt user with a custom message on cursor focus on the input field

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#330]
**Is your feature request related to a problem? Please describe.**
We are looking for a feature to allow the developer to prompt the user on cursor focus on the input field

We have 2 use cases:
- User needs to be prompted to enter a minimum characters before the list is displayed in the autocomplete (js only, see screenshot)
![PixelSnap 2022-07-25 at 10 42 47](https://user-images.githubusercontent.com/5403134/180748092-8b21c377-8648-4cd9-9275-f86d552b75da.png)

- User has to complete another dependent field before they can search in the autocomplete
![PixelSnap 2022-07-25 at 10 05 46](https://user-images.githubusercontent.com/5403134/180748489-585983e3-65f8-46bb-a4bf-2acbc79c1120.png)

**Describe the solution you'd like**
I suggest the following additional props to enable above feature request

- minChars
- minCharsMessage
- promptMessage
- promptCondition

Please follow the following steps to create your branch:
```bash
git checkout release/0.5
git pull
git checkout -b 'feature/autocomplete-cursor'
```

**Comment by daniele-zurico** [comment]
fixed by #336
