### ISSUE TITLE
Button: add value property

### ISSUE THREAD

**Issue by szilvihorvath** [Capgemini/dcx-react-library#332]
**Describe the bug**
TypeScript is complaining when value property is passed in to the Button component as it is not one of its properties

The setting of the value needs to be surfaced on the <Button /> component

```
<button
      onClick={handleClick}
      disabled={disable}
      type={type}
      aria-label={ariaLabel}
      value={value} // THIS IS A NEW ATTRIBUTE
      {...props}
    >
      {prefix}
      {isLoading && loadingLabel ? loadingLabel : label}
      {postfix}
    </button>
```

**To Reproduce**
1. pass in value property to Button
2. See TS complaining 😬

![Screenshot 2022-07-25 at 17 36 14](https://user-images.githubusercontent.com/50360435/180829887-ecf512ca-eb4e-44a8-9289-2658effbd011.png)

Please follow the following instruction to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'feature/button-value'
```

**Comment by daniele-zurico** [comment]
closed by #342
