### ISSUE TITLE
FormSelect: containerId prop

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#335]
**Is your feature request related to a problem? Please describe.**
I am looking for a new prop called something like containerId (similar to containerClassName) to be used as in id attribute on the most outer div of this component ) - similar to containerClassName prop.

**Describe the solution you'd like**
A new prop called something like containerId (similar to containerClassName) on the most outer div of this component ) on the same level as containerClassName)

**Describe alternatives you've considered**
Wrapping a div around the component in order to add an ID

Please follow the following instruction to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'release/select-containerId'
```

**Comment by daniele-zurico** [comment]
hi @brightpixels 
what about if we give you new props called:
```ts
 containerProps?: any;
```
then you decide what to do with it?

**Comment by brightpixels** [comment]
> hi @brightpixels what about if we give you new props called:
> 
> ```ts
>  containerProps?: any;
> ```
> 
> then you decide what to do with it?

Even better. Thanks

**Comment by daniele-zurico** [comment]
@brightpixels this ticket has been implemented in this release. If you need it I can create a beta-1
#350
