### ISSUE TITLE
Autocomplete - Pressing Enter when the field is empty throws an error

### ISSUE THREAD

**Issue by sri-viswanathan** [Capgemini/dcx-react-library#354]
**Describe the bug**
With JS enabled and when the Autocomplete field is empty and is in focus, when the user presses the Enter key an error is thrown:
```
TypeError: Cannot read properties of undefined (reading 'trim')
```

**To Reproduce**
1. Go to a page in an app that uses the Autocomplete component
2. Click on the Autocomplete field
3. Ensure that the Autocomplete field is empty
4. Press the Enter key
5. See an error

**Expected behavior**
Pressing Enter when the field is empty should not throw an error.  There should be no effect.

**Additional context**
Requires a null check or ensuring the internal state is at least an empty string

Please follow the following instruction to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'feature/autocomplete-field-empty'
```

**Comment by daniele-zurico** [comment]
Closed by PR #358
