### ISSUE TITLE
Autocomplete - Prompt appears on initial page load even when component does not have focus

### ISSUE THREAD

**Issue by sri-viswanathan** [Capgemini/dcx-react-library#355]
**Describe the bug**
The `promptMessage` appears on initial page load even when the component does not have focus

**To Reproduce**
1. Go to a page in an app that uses the Autocomplete component and where it does not receive focus on page load
2. Ensure that the Autocomplete component is set up to display a `promptMessage` based on a `promptCondition`
3. Refresh the page
4. Note that the `promptMessage` is visible even though the Autocomplete component does not have focus

**Expected behavior**
The `promptMessage` and `promptCondition` should kick in only when the Autocomplete field explicitly has focus.

Please follow the following instruction to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'feature/autocomplete-prompt
```

**Comment by daniele-zurico** [comment]
Closed by #357
