### ISSUE TITLE
Add configurable id to Autocomplete Result items <li/>

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#363]
**Is your feature request related to a problem? Please describe.**
On the <Autocomplete /> there needs to be a way of adding an id to each <li/> within the <ul/> so that each item within the list can be identified.

**Describe the solution you'd like**
```tsx
          <li
            id={`${liContainerId}--${index}`} // <--- THIS IS WHAT IS NEEDED
            className={
              index === activeOption && activeClass
                ? [activeClass, liContainerClass].join(' ')
                : [
                    liContainerClass,
                    index % 2 === 0
                      ? `${liContainerClass}--even`
                      : `${liContainerClass}--odd`,
                  ].join(' ')
            }
            key={optionName}
            onClick={onClick}
            style={liContainerStyle}
          >
            {optionName}
          </li>
```

**Additional context**
Specie list - id="species_option--0"; id="species_option--1"...etc
Product favorite Page
Add product from favorite list - id="product_option--0"; id="product_option--1"...etc.... when we have at least one product in the favorite list

**Comment by daniele-zurico** [comment]
PR created: https://github.com/Capgemini/dcx-react-library/pull/364
