### ISSUE TITLE
FormGroup: need to be able to set items div wrapper/group classname

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#367]
**Describe the bug**
The FromGroup items are wrapped with a div but there is no option/prop to set the class in this div. I propose a prop called "itemGroupClassName"

**To Reproduce**
Use the FormGroup in a React app and observe the div wrapping the list of radios/checkboxes and attempt to set a class name for this wrapping container

**Expected behavior**
To be able to set a class name on the div wrapping the list of items/radios/checkboxes

Please follow the following instruction to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'feature/form-wrapper-classname'
```

**Comment by cg-julian-taylor** [comment]
I believe a property for this already exists.

On the `<FormGroup/>` component there is a `itemClassName` prop that is passed down as seen in the image below.

fieldset > div.itemsClasses > div.itemClassName is the one I believe we are trying to resolve.

(I used `itemsClasses` and `itemClassName` as classes to help identify which props are being passed).

<img width="570" alt="Screenshot 2022-12-14 at 11 30 00" src="https://user-images.githubusercontent.com/107050226/207584167-0055ccc1-fa61-4b6e-b36d-e13c0e9ba1bf.png">

If I have understood this correctly then there isn't a need for a code change but perhaps renaming the props and adding to documentation may clear up future confusion?

**Comment by brightpixels** [comment]
@cg-julian-taylor you are right :)  We can close this one.
