### ISSUE TITLE
Occasional test failure (src/button/__tests__/Button.test.tsx)

### ISSUE THREAD

**Issue by cg-julian-taylor** [Capgemini/dcx-react-library#379]
**Describe the bug**
On occasion when running `yarn test` (src/button/__tests__/Button.test.tsx) fails on line 136.
Could be related to the `handleClick()` setTimeout.

**To Reproduce**
1. Run `yarn test`
2. Keep running the above command until (src/button/__tests__/Button.test.tsx) fails (line 136).

**Expected behavior**
The test should run every time. However on occasions it fails.

**Screenshots**
<img width="937" alt="Screenshot 2022-12-20 at 11 56 02" src="https://user-images.githubusercontent.com/107050226/208661537-3477a7af-1954-4771-91dc-bb2dc37fda52.png">

**Additional context**
Occurs in CLI

```bash
git checkout release/0.8
git pull
git checkout -b 'feature/fix-random-failure-test'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/673
