### ISSUE TITLE
Radio / checkbox group missing from example src

### ISSUE THREAD

**Issue by cg-julian-taylor** [Capgemini/dcx-react-library#384]
**Describe the bug**
Recent work conducted as part of [this branch](https://github.com/Capgemini/dcx-react-library/issues/353) did not factor in updating code in the example directory to use the replaced components.

**To Reproduce**
1. Open terminal
2. Go to root
3. `yarn dev`
4. Open new terminal
5. `Cd example`
6. `yarn start`

**Expected behavior**
Running yarn start in the example dir should compile without issue.

**Comment by daniele-zurico** [comment]
solved by PR
