### ISSUE TITLE
Autocomplete: Selecting a dropdown option with the mouse no longer works

### ISSUE THREAD

**Issue by sri-viswanathan** [Capgemini/dcx-react-library#399]
**Describe the bug**
After typing the minimum number of characters required to display the options list, using a mouse to choose an option no longer works

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the `release/0.6` branch or create a branch off of it
2. Go to a page that uses the Autocomplete component or start up Storybook for this library
3. Type in the minimum characters required to display the options list
4. Hover over an option and click on it to select
5. The options list disappears but the option has not been selected and the input still contains the original characters that were typed in

**Expected behavior**
This used to work properly but is now broken.  Choosing an option from the list should cause the options list to disappear and the chosen option should appear in the input field

Please follow the following instructions to create the new branch:
```bash
git checkout release/0.6
git pull
git checkout -b 'feature/<issueNumber>-autocomplete-mouse-select'
```

**Comment by daniele-zurico** [comment]
merged #400
