### ISSUE TITLE
Text character count

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#414]
Some of our text input have a limit. To help users, it would be great to be able to specify how many characters left before the user hits the limit. We are using this library GDS styling so something like this would be great: https://design-system.service.gov.uk/components/character-count/

Key features:
- Developer should be able to specify the character limit number
- Developer should be able to pass in the character limit prompt message (one when JS is enabled, and another for when non-js is disabled)
- HTML structure should match GDS markup (with ability to set css classes) or the developer should be able to specify the HTML markup
- Character should count down when JS is enabled

Progressive enhancements:
- Please take into account how this component behaves without javascript
- Without Javascript, the prompt message should be static
- With Javascript, the prompt message should be dynamic to inform use how many characters left

**Comment by daniele-zurico** [comment]
closed by #419
