### ISSUE TITLE
Discovery: Look into Table component and is fit-for-purpose

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#417]
Currently, the library is actively used, specially by projects that adhere to GDS https://design-system.service.gov.uk/styles/

However, there is not much take up the Table component.

Look into potential reasons and potential changes that can increase the usage of this component.

**Comment by daniele-zurico** [comment]
@brightpixels I'm wondering who should look on that :) I suggest to create a ticket that is workable.... closing for now
