### ISSUE TITLE
Provide a prop for sorting results within the Autocomplete

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#422]
Within the autocomplete compenent, I would like to control the way that results are ordered by providing the autocomplete component with an _optional_ search function.

Currently results are ordered in the same order that they are given within the `options` prop, however I would like to have the results ordered by specified ranking function that is passed to the autocomplete as an _optional_ prop.

```tsx
// we need a way to sort the array of strings within filtered, 
// based on a provided search function passed in as a prop 
const filtered = options.filter((optionsName) =>
 optionsName.toLowerCase().includes(value.toLowerCase())
);
```
for example:

```tsx
  quickSearch = (value: string) => {
    const queryStr = value.toLowerCase();
    options.toLowerCase().includes(queryStr);

    const filtered: string[] = options
      .filter((optionsName: string) => optionsName.toLowerCase().includes(value.toLowerCase()))
      .sort((a: string, b: string) => {
        // code that will sort the valid results
    });

    return filtered;
  };
  
  <Autocomplete 
    .. // usualy props
    search={this.quickSearch}
  />
```

If a search function is not provided the autocomplete should display results as it is currently doing.

**Comment by daniele-zurico** [comment]
Closed by #423
