### ISSUE TITLE
Add feature to customise the character count messages.

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#424]
We need to be able to customise these messages so that we can translate this text:

- Please offer a way for consumers to be able to specify their own dynamic messages using the `maxLength`, `limitType`, `remainingCount` and `overLimitBy` variables for each of these scenarios.

```tsx
  const maxCharactersMessage = !hydrated
    ? `You can enter up to ${maxLength} ${limitType}.` // non-js
    : remainingCount >= 0
    ? `You have ${remainingCount} ${limitType} remaining` // js within the limit
    : `You have ${overLimitBy} ${limitType} too many`; // js outside the limit
```

**Comment by daniele-zurico** [comment]
closed by #428
