### ISSUE TITLE
AutoComplete: accessibilty using tab and up/down

### ISSUE THREAD

**Issue by brightpixels** [Capgemini/dcx-react-library#436]
**Describe the bug**
Items from the Autocomplete drop down can't be selected/navigated with tab and up/down arrows.
Our client has highlighted this as an issue since the current autocomplete works with tab and up/down arrows.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the AutoComplete component in a React app
2. Attempt to select/navigate items from the drop down with tab and up/down arrows.

**Expected behaviour**
Items from the Autocomplete drop down to be selected/navigated with tab and up/down arrows.

**Comment by daniele-zurico** [comment]
the component already offer the functionality please do this:
```html
resultActiveClass="autocomplete__option--focused"
```
