### ISSUE TITLE
Details component - Please add prop for an id 

### ISSUE THREAD

**Issue by arpakuma** [Capgemini/dcx-react-library#438]
**Is your feature request related to a problem? Please describe.**
I need to add 'id' prop on the summary -> span tag for automation testing.

**Describe the solution you'd like**
Please add a property **summaryTextId** (similar to summaryTextClassName) 

<  Details
  summary="Help with nationality"
  .......
  summaryTextClassName="summar-text-class-name"
  **summaryTextId="summary-text-id"**
  .......
 >

**Additional context**

**Comment by daniele-zurico** [comment]
I suggest to add another props called: 
```ts
summaryProps?: any
``` 
in this way you can extend it as much as you want

**Comment by daniele-zurico** [comment]
closed by #442
