### ISSUE TITLE
Heading

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#450]
As a developer
I want to be able use a `Heading` component
so that I can easily add a title

The component should contain:
- [ ] Embedded className called `dcx-heading dcx-heading-${level}`
- [ ] Relevant classes for shared / reusable styling
- [ ] Add the ability to specify other props (...props)
- [ ] Add prop called label to display the content of title
- [ ] Add prop called level to denote the <h> tag that should be used, from h1 to h6

The final user will use in this way:
```tsx
<Heading className="title" label="title text" id="user-defined-id" level="1" />
```

Tasks:
- [ ] Add unit tests
- [ ] Add Application code with commented props
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx) in a section called Typography
- [ ] Add to live demo

Please follow the below to create your branch

```bash
git checkout release/0.8
git pull
git checkout -b 'feature/heading'
```

**Comment by daniele-zurico** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/482
