### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#451]
As a developer
I want to be able use a `Label` component
so that I can easily add a label

Component should contain relevant classes for shared / resuable styling

The component should contain:
- [x] embedded className called `dcx-label`
- [x] relevant classes for shared / reusable styling
- [x] the ability to specify the value of the label 
- [x] Add the ability to specify other props (...props)

The final user will use in this way:
```tsx
<Label className="additional classes" value="text" id="user-defined-id" />
```

Tasks:
- [x] Add unit tests
- [x] Add Application code with commented props
- [x] Add Demo use of component
- [x] Add to storybook documentation file with examples (.mdx) in a section called Typography
- [x] Add to live demo

Please follow the below to create your branch

```bash
git checkout release/0.8
git pull
git checkout -b 'feature/label'
```

**Comment by daniele-zurico** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/483
