### ISSUE TITLE
Insert Text

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#452]
As a developer
I want to be able use a `Insert Text` component
so that I can easily add a insert text

Component should contain relevant classes for shared / resuable styling

The component should contain:
- [ ] Embedded className called `dcx-insert-text`
- [ ] InsertText behind the scenes is a a div:
```tsx
<div class="dcx-insert-text">
  insert text
</div>
```
- [ ] Relevant classes for shared / reusable styling
- [ ] Add the ability to specify other props (...props)
- [ ] Add prop called value to display the text for insert-text

The final user will use in this way:
```tsx
<InsertText value="insert text" id="user-defined-id" />
```

Tasks:
- [ ] #480
- [ ] Add Application code with commented props
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx) in a section called Typography
- [ ] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/insert-text'
```

**Comment by daniele-zurico** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/491
