### ISSUE TITLE
Ordered List

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#454]
As a developer
I want to be able use a `Ordered List item` component
so that I can easily add a ordered list item

Component should contain relevant classes for shared / resuable styling

Tasks:
- [ ] Add unit tests
- [ ] Add Application code with commented props
- [ ] Add the ability to specify other props (...props)
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx)
- [ ] Add to live demo

for example
```tsx
<OrderedList>
  <ListItem>
    List item example
  </ListItem>
</OrderedList>
```

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/ordered-list'
```

**Comment by daniele-zurico** [comment]
overlap with another story
