### ISSUE TITLE
Paragraph

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#455]
As a developer
I want to be able use a `Paragraph` component
so that I can easily add a paragraph

The component should contain:
- [x] embedded className called `dcx-paragraph`
- [x] relevant classes for shared / reusable styling
- [x] the ability to specify the value of the label 
- [x]  the ability to specify other props (...props)

 Paragraph behind the scenes is a `p` tag:
```html
<p>some text</p>
```

The final user will use in this way:
```tsx
<Paragraph className="paragraph" value="paragraph text" {...props}/>
```
and the outcome will be something like this:

```html
<p class="dcx-paragraph paragraph">paragraph text</p>
```
Tasks:
- [ ] Add unit tests
- [ ] Add Application code with commented props
- [ ] Add the ability to specify other props (...props)
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [ ] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/paragraph'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/479
