### ISSUE TITLE
CharacterCount component - not resetting the red font colour after valid input

### ISSUE THREAD

**Issue by arpakuma** [Capgemini/dcx-react-library#463]
**Describe the bug**
CharacterCount component not resetting the error class once the input is edited.

**To Reproduce**
1. Go to CharacterCount component
2. Enter characters beyond maxlength (suppose maxlength is 50), You see the error message in red- You have 4 characters too many.
3. Now edit the characters to make it under maxlength (50) 
4. The text below should reset back to black colour.

**Expected behavior**
When input characters are edited back to be inside maxlength limit, the text below should be displayed in Black colur (remove the error class)

**Screenshots**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/128031818/231843267-3fcd1268-487d-4971-ac04-77ade60b1c70.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/471
