### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#467]
As a developer
I want to be able use a `Link` component
so that I can easily add a link

The component should contain:
- [x] embedded className called `dcx-link`
- [x] relevant classes for shared / reusable styling
- [x] the ability to specify the value of the label 
- [x] the ability to specify other props (...props)

Link behind the scenes is an `a` anchor tag:
```html
<a>some text</a>
```

The final user will use in this way:
```tsx
<Link to={{ link }} {...props}/>
```

Tasks:
- [x] Add unit tests
- [x] Add Application code with commented props
- [x] Add the ability to specify other props (...props)
- [x] Add Demo use of component
- [x] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [x] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/link'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/494
