### ISSUE TITLE
Autocomplete doesn't auto scroll for filtered list on keydown

### ISSUE THREAD

**Issue by peter-uzor-capgem** [Capgemini/dcx-react-library#470]
**Describe the bug**
The autocomplete component result scroll does not scroll when navigating using the arrow keys

**To Reproduce**
1. Go to Autocomplete
2. Enter one letter to return options which exceed the size of the results container and would require scroll
3. Tap the down arrow on the keyboard to proceed to the bottom options
4. You will notice that the active option will go below out of view with the scroll not following

**Expected behavior**
The active option should always be within view of he user. Therefore scroll should follow option selection on keydown

**Screenshots**
<img width="1083" alt="Screenshot 2023-05-05 at 10 05 03" src="https://user-images.githubusercontent.com/120393762/236419672-083d43ac-33be-4f0d-ad27-299400623d4b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version 112.0.5615.137

**Additional context**

**Comment by daniele-zurico** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/472
