### ISSUE TITLE
Abbreviate

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#497]
As a developer
I want to be able use a `Abbreviate` component
so that I can easily add an abbreviate

The component should contain:
- [x] embedded className called `dcx-abbreviate`
- [x] relevant classes for shared / reusable styling
- [x] the ability to specify the value of the label 
- [x]  the ability to specify other props (...props)

Abbreviate behind the scenes is a `abbr` tag:
```html
<abbr title="World Health Organization">WHO</abbr>
```

The final user will use in this way:
```tsx
<Abbreviate title="World Health Organization">WHO</Abbreviate>
```
and the outcome will be something like this:

```html
<abbr title="World Health Organization">WHO</abbr>
```
Tasks:
- [x] Add unit tests
- [x] Add Application code with commented props
- [x] Add the ability to specify other props (...props)
- [x] Add Demo use of component
- [x] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [x] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/abbreviate'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/512
