### ISSUE TITLE
Code snippet

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#500]
As a developer
I want to be able use a `Code` component
so that I can easily add code snippets

The component should contain:
- [x] embedded className called `dcx-code`
- [x] relevant classes for shared / reusable styling
- [x] the ability to specify the value of the label 
- [x]  the ability to specify other props (...props)

Code snippet behind the scenes is a `code` tag:
```html
<code>code</code>
```

The final user will use in this way:
```tsx
<CodeSnippet>my code</CodeSnippet>
```
and the outcome will be something like this:

```html
<code>code</code>
```
Tasks:
- [x] Add unit tests
- [x] Add Application code with commented props
- [x] Add the ability to specify other props (...props)
- [x] Add Demo use of component
- [x] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [x] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/code'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/507
