### ISSUE TITLE
Description List

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#502]
As a developer
I want to be able use a `DescriptionList` component
so that I can easily add keyboard shortcuts

The component should contain:
- [ ] embedded className called `dcx-description-list`
- [ ] relevant classes for shared / reusable styling
- [ ] the ability to specify the value of the label 
- [ ] the ability to specify other props (...props)

DescriptionList behind the scenes is a `dl` tag:
```html
<dl>
    <dt>Coffee</dt>
    <dd>- black hot drink</dd>
    <dt>Milk</dt>
    <dd>- white cold drink</dd>
</dl> 
```

The final user will use in this way:
```tsx
<DescriptionList>
 <Term>Coffee</Term>
 <Detail>- black hot drink</Detail>
 <Term>Milk</Term>
 <Detail>- white cold drink</Detail>
</DescriptionList>
```
and the outcome will be something like this:

```html
<dl>
    <dt>Coffee</dt>
    <dd>- black hot drink</dd>
    <dt>Milk</dt>
    <dd>- white cold drink</dd>
</dl> 
```
Tasks:
- [ ] Add unit tests
- [ ] Add Application code with commented props
- [ ] Add the ability to specify other props (...props)
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [ ] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/description-list'
```

**Comment by daniele-zurico** [comment]
closed by #522
