### ISSUE TITLE
Preformatted Text

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#503]
As a developer
I want to be able use a `PreformattedText` component
so that I can easily add a preformatted text element

The component should contain:
- [ ] embedded className called `dcx-pre`
- [ ] relevant classes for shared / reusable styling
- [ ] the ability to specify the value of the label 
- [ ]  the ability to specify other props (...props)

PreformattedText behind the scenes is a `pre` tag:
```html
<pre>
Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks.
</pre>
```

The final user will use in this way:
```tsx
<PreformattedText class="">Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks.</PreformattedText>
```
and the outcome will be something like this:

```html
<pre>
Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks.
</pre>
```
Tasks:
- [ ] Add unit tests
- [ ] Add Application code with commented props
- [ ] Add the ability to specify other props (...props)
- [ ] Add Demo use of component
- [ ] Add to storybook documentation file with examples (.mdx)  in a section called Typography
- [ ] Add to live demo

Please follow the below to create your branch
```bash
git checkout release/0.8
git pull
git checkout -b 'feature/pre'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/511
