### ISSUE TITLE
Group new components within Storybook

### ISSUE THREAD

**Issue by daiseybtw** [Capgemini/dcx-react-library#513]
When browsing the storybook, some components are nicely grouped, such as form and typography, but there are some components at the root level that could also be grouped to make things clearer.

It would be really nice if the components at the root level could be grouped into relevant categories, e.g Details, Breadcrumb, Tabs and Table could be grouped into a 'Layout' folder, and going forward, seeing if any new components fit into a new or existing category.

Please follow the below to create your branch

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/storybook-layout'
```

**Comment by daiseybtw** [comment]
For example, we have Typography and Form that contain components but then others at a top level 
<img width="240" alt="image" src="https://github.com/Capgemini/dcx-react-library/assets/97960080/d5f01977-7c7a-4657-87ce-b75db1274527">

**Comment by shivammuttoo** [comment]
@daiseybtw Could you please suggest the exact root folder for each component that is not currently?

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/561
