### ISSUE TITLE
Code Snippet - Design System

### ISSUE THREAD

**Issue by cg-mmirca** [Capgemini/dcx-react-library#532]
## Prerequisites

* Abbreviate element will have the `.dcx-code` class name

## Overview

Possible states:
* Default

Variants:
No variants

Keeping in mind we have the elements:
| Element | Description | Token Name |
| --- | ---| --- |
| Text | The text itself, should match regular body styles but have different font family | pre_body |
| Box | The box containing the text, it's common to have a display inline-block. We could add some small padding and background color | pre_box |

## Design ideas

<img width="425" alt="Screenshot 2023-09-22 at 09 57 49" src="https://github.com/Capgemini/dcx-react-library/assets/92944005/92e101c6-da12-480b-a865-a4b5beddacd0">

## Storybook

Create the pages for:
* Playground
* Default
* AccessibleTheme
* DarkTheme
* MaterialTheme

On each MDX page make examples for:
* Default code snippet

## Token definition

Considerations:
* Take as reference the Paragraph component
* Add the tokens to `src/design-system/tokens.json`
* Define all styles in `src/design-system/code-snippet.css`
* Add import to the new CSS file in `src/design-system/index.css`

Possible tokens:
* color-text-pre_body
* font-family-pre_body
* font-weight-pre_body
* font-size-pre_body
* color-background-pre_box
* spacing-pre_box
* etc.

Follow the naming pattern:
```text
[token_category]-[property]-[element]-[variant]-[state]
```

F.e. for `font-size-body` we have:
* **category:** font
* **property:** size
* **element:** pre_body
* **variant:** default -> not necessary to show in name
* **state:** default -> not necessary to show in name

Please follow these steps to create your branch:

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/ds-code-snippet'
```

**Comment by jgonza16** [comment]
Closed with https://github.com/Capgemini/dcx-react-library/pull/543
