### ISSUE TITLE
Preformatted Text - Design System

### ISSUE THREAD

**Issue by cg-mmirca** [Capgemini/dcx-react-library#536]
# PreformattedText - Design System

## 1 - Prerequisites

* Host element will have the `.dcx-pre` class name

### 2.1 - Possible states

| Name | Description |
| --- | --- |
| Default | Instance without specific properties defined |

### 2.2 - Variants

No variants

### 2.3 - Structure

| Element | Description | Token Name |
| --- | ---| --- |
| Text | The text itself  | pre_body |
| Box | The box that surrounds the text. This a block element.  | pre_box |

The difference with `CodeSnippet` element is that this one is an block element. It can have box styles such as padding.

### 2.4 - Tokens definition

Considerations:
* Take as reference the Paragraph and CodeSnippet components
* Add the tokens to `src/design-system/tokens.json`
* Define all styles in `src/design-system/preformatted-text.css`
* Add import to the new CSS file in `src/design-system/index.css`

Possible tokens:
* color-text-pre_body
* color-background-pre_box
* font-family-pre_body
* etc.

Note that this element is similar to `CodeSnippet` Consider using similar token values for size.

Follow the [naming pattern](https://github.com/Capgemini/dcx-react-library/wiki/Contributing#11---naming-pattern)

## 3 - Storybook

Create the pages for:
* Playground
* Default
* AccessibleTheme
* DarkTheme
* MaterialTheme

On each MDX page make examples for each possible variant

## 4 - Initial setup

Please follow these steps to create your branch:

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/preformatted-text'
```

**Comment by mmirca** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/575
