### ISSUE TITLE
Skeleton - Design System

### ISSUE THREAD

**Issue by daniele-zurico** [Capgemini/dcx-react-library#553]
# Skeleton - Design System

## 1 - Prerequisites

- Host element will have the `.dcx-skeleton` class name
- Host element will have conditional classes for all variants `.dcx-skeleton-variant-{text | circular | rectangular | rounded}` class name.
- Host element will have conditional classes for both animations `.dcx-skeleton-animation-{wave | pulsate}` class name.

### 2.1 - Possible states

| Name    | Description                                  |
| ------- | -------------------------------------------- |
| Default | Instance without specific properties defined |

### 2.2 - Variants

| Name        | Description             |
| ----------- | ----------------------- |
| text        | text look & feel        |
| circular    | circular look & feel    |
| rectangular | rectangular look & feel |
| rounded     | rounded look & feel     |

### 2.3 - Structure

| Element  | Description                |  Token Name |
| -------- | -------------------------- | ----------- |
| Skeleton | The host element container |  skeleton   |

When developing take a close look to the FormInput component. It is a form element as well, the tokens and styling approach should be similar.

### 2.4 - Tokens definition

Considerations:

- ❗ Take a close look to the FormInput component. It is a form element as well, the tokens and styling approach should be similar.
- Add the tokens to `src/design-system/tokens.json`
- Define all styles in `src/design-system/skeleton.css`
- Add import to the new CSS file in `src/design-system/index.css`

Possible tokens:

- color-background-skeleton
- animation-skeleton-wave
- animation-skeleton-pulsate
- etc.

Follow the [naming pattern](https://github.com/Capgemini/dcx-react-library/wiki/Contributing#11---naming-pattern)

## 3 - Storybook

Create the pages for:

- Playground
- Default
- AccessibleTheme
- DarkTheme
- MaterialTheme

On each MDX page make examples for each possible variant

## 4 - Initial setup

Please follow these steps to create your branch:

```bash
git checkout release/1.1.0
git pull
git checkout -b 'feature/skeleton-design-system'
```

**Comment by jgonza16** [comment]
closed with https://github.com/Capgemini/dcx-react-library/pull/676
