### ISSUE TITLE
Design base css needs to use token

### ISSUE THREAD

**Issue by alexwbbr** [Capgemini/dcx-react-library#560]
The design systems base css is currently using a hard coded value for the font family instead of the token "font-family-body" this needs to be updated to allow users to set the base font family for the entire website.

**Comment by cg-mmirca** [comment]
Hi @alexwbbr,

Thank you for reaching out. The font styles should still be customisable with the current version of the library.

I created a test project to showcase this feature:

<img width="2560" alt="Screenshot 2023-10-24 at 17 40 11" src="https://github.com/Capgemini/dcx-react-library/assets/92944005/b82b93dd-e540-49c9-b476-86f011a5b5df">

You would need to update the global styles to provide your own custom font definition for the `html` element.

**Comment by alexwbbr** [comment]
@cg-mmirca thanks for the reply!

Whilst you can overwrite the global value what is the point of having a global-font token if it's not used in the html or body tag?  How often is a website using two different font's for the main body and it's buttons or paragraphs for example. I still think the hard coded value should be replaced with the token otherwise what point is there in the tokens if people just overwrite the classes directly?

**Comment by daniele-zurico** [comment]
closed as not needed for now
