### ISSUE TITLE
Paragraph - enable paragraph to have a custom content

### ISSUE THREAD

**Issue by daniele-zurico** [Capgemini/dcx-react-library#566]
Currently, the paragraph component allows only to have a `value` however it should allow it to contain custom content something like:
```html
<Paragragraph>
   <ImCustomComponent>
</Paragraph>
```
The current paragraph however is already used in production so we can't remove the `value` property the only thing we can do is to extend the use by adding this extra ability.
We need to make sure however that is you using the new function you not using the old one so something like this:
```html
<Paragragraph value="im the value">
   <ImCustomComponent>
</Paragraph>
```
will not happen.

- [ ] make the change in the src/abbreviate/Abbreviate.tsx adding the property
- [ ] make sure that if children is passed you can't use `value` as well and vice-versa
- [ ] make the change in the src/abbreviate/tests/Abbreviate.test.tsx adding the test to cover the use case
- [ ] change all the storybook sections to add the documentation

**Comment by daniele-zurico** [comment]
an Idea on how it can be implemented
```jsx
type BaseProps = {
  test: string;
  a?: string;
  b?: string;
};

type PropsA = BaseProps & { a: string };
type PropsB = BaseProps & { b: string };

type Props = PropsA | PropsB;

function Component(props: Props) {
  if (props.a) {
    // do something
  }

  if (props.b) {
    // do something
  }

  return null;
} 
```

**Comment by kjzweerts** [comment]
This looks like arbitrary composition. Have the Paragraph accept a prop that is either of type 'value' or another component.

```jsx
function Component({value, children}) {

    return (
        <Paragraph value={<AnotherComponent />} />
        <Paragraph value={"A string as p text"} />
    )
}
````

**Comment by jgonza16** [comment]
you suggest only one way with prop value. this approach makes the component less complex but i feel more natural the paragraph  works like higher-order component. I think we will use this more.

```jsx
<Paragraph>
  This is the simple custom-content of the
  <strong>
    paragraph
  </strong>
</Paragraph>
```
@kjzweerts you can review https://github.com/Capgemini/dcx-react-library/pull/567 and you get feedback.

**Comment by daniele-zurico** [comment]
hi @kjzweerts thanks for your comment and I think your point is valid however I do agree with @jgonza16 .... it will looks more natural to use the component like an html native component: 
```html
<Paragraph>content</Paragraph>
```
the only reason we want to leave `value` property there is because some other projects are already using the Paragraph and we don't want to introduce a breaking change

**Comment by kjzweerts** [comment]
> On the other side can I ask you if you using the library? just out of curiosity

No I am not a user. I am in an Angular project and my react knowledge is starting to get vague 😅.
So I’m maybe looking to contribute to have best of both worlds.

I work for Sogeti and found this when browsing GitHub.

**Comment by daniele-zurico** [comment]
absolutely @kjzweerts ... let me know when you want to get involved and in which way and we can discuss a ticket as starting point. Feel free to contact me on msTeam

**Comment by daniele-zurico** [comment]
Closed by https://github.com/Capgemini/dcx-react-library/pull/567
