### ISSUE TITLE
Radio Button - Design System

### ISSUE THREAD

**Issue by mmirca** [Capgemini/dcx-react-library#580]
# Radio Button - Design System

## 1 - Prerequisites

* Host element will have the `.dcx-radio-button` class name
* Host element will have conditional classes for error state `.dcx-radio-button--error` class name

### 2.1 - Possible states

| Name | Description |
| --- | --- |
| Default | Instance without specific properties defined |
| Disabled | Instance with native input disabled |
| Filled (Checked) | Instance with value |
| Focus | Instance while receiving focus on native input |
| Error | Instance with validation errors |

### 2.2 - Variants

| Name | Description |
| --- | --- |
| Default | Default look & feel |

### 2.3 - Structure

| Element | Description | Token Name |
| --- | ---| --- |
| InputBox | The native input itself  | formcontrol |
| Label | The label element  | formcontrol_label |

When developing take a close look to the FormSelect component. It is a form element as well, the tokens and styling approach should be similar.

### 2.4 - Tokens definition

Considerations:
*  ❗ Take a close look to the FormSelect component. It is a form element as well, the tokens and styling approach should be similar.
* Add the tokens to `src/design-system/tokens.json`
* Define all styles in `src/design-system/radio-button.css`
* Add import to the new CSS file in `src/design-system/index.css`

Possible tokens:
* color-text-formcontrol
* color-text-formcontrol-error
* color-text-formcontrol-filled
* color-text-formcontrol_label
* color-text-formcontrol_label-filled
* color-text-formcontrol_label-error
* etc.

Follow the [naming pattern](https://github.com/Capgemini/dcx-react-library/wiki/Contributing#11---naming-pattern)

## 3 - Storybook

Create the pages for:
* Playground
* Default
* AccessibleTheme
* DarkTheme
* MaterialTheme

On each MDX page make examples for each possible variant

## 4 - Initial setup

Please follow these steps to create your branch:

```bash
git checkout release/1.0.0
git pull
git checkout -b 'feature/radio-button-design-system'
```

**Comment by jgonza16** [comment]
Component is deprecated. we do https://github.com/Capgemini/dcx-react-library/issues/608 instead of this.
