### ISSUE TITLE
Table - customHeaderLabels - Further Customisation

### ISSUE THREAD

**Issue by daiseybtw** [Capgemini/dcx-react-library#582]
**Background**

When creating tables, sometimes each custom header label needs slightly different styling, such as text alignment.

**Enhancement request:**
Currently when providing custom header labels, we get a table looking like the following:

<img width="719" alt="Screenshot 2023-12-05 at 15 40 24" src="https://github.com/Capgemini/dcx-react-library/assets/97960080/b813e9d3-90f4-45bc-bf8c-7633953708fc">

It would be fantastic if we could provide either class names, custom css etc on a per header label so that we can achieve an outcome like this (in this case, header label 3 is text-aligned to the right):

<img width="727" alt="Screenshot 2023-12-05 at 15 40 28" src="https://github.com/Capgemini/dcx-react-library/assets/97960080/dc87b42f-78c4-48b8-8c9c-4d077a9c329c">

We will add more attributes to provide the ability to add these classNames:
```jsx
customTheadClassName ={['class1', 'class2', 'class3']}
customTrClassName ={['class1', 'class2', 'class3']}
customThClassName ={['class1', 'class2', 'class3']}
customTbodyClassName ={['class1', 'class2', 'class3']}
customTdClassName ={['class1', 'class2', 'class3']}
```

Please follow these steps to create your branch:
```bash
git checkout release/1.1.0
git pull
git checkout -b 'feature/custom-header-labels-improvements'
```

**Comment by daniele-zurico** [comment]
Are you proposing to have something like this? :
```tsx
<Table
  dataSource={ELEMENT_DATA}
  customTheadClassName ={['class1', 'class2', 'class3']}
  customTrClassName ={['class1', 'class2', 'class3']}
 customThClassName ={['class1', 'class2', 'class3']}
 customTbodyClassName ={['class1', 'class2', 'class3']}
 customTdClassName ={['class1', 'class2', 'class3']}
```

**Comment by daiseybtw** [comment]
I would say we could improve `CustomHeaderLabel[]`, so it would be as simple as:

```
...
label: 'foo'
customClass: 'bar'
```

and then wrapping the header label in `customClass`

**Comment by daniele-zurico** [comment]
the question will be if your header on the last column is aligned on the right hand side, you don't want as well to align the body?

**Comment by daiseybtw** [comment]
You could and it would be another good addition, in my use case we are providing a custom element into the last column body so we apply styles that way.

**Comment by alexwbbr** [comment]
The customTheadClassName is not needed as you can only have one thead element per table. customTrClassName also poses an issue as is this the tr elements in the header, body or both? See example below where they use the tr element in the header:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

**Comment by Ahmet-K** [comment]
The existing ticket doesn't explicitly state that those classes in `customThClassName` have to be applied to the specific TH element.

If so, it does not specify what should happen if the number of classes in `customThClassName` does not match the number of `<th>` elements. For example, what should happen if there are more `<th>` elements than classes or vice versa?

**Comment by alexwbbr** [comment]
I am closing this ticket, I do not believe this functionality is needed for the majority of users. Any one who needs to style a specific element of the table can do so with css selectors.
