### ISSUE TITLE
remove CRA from Example and replace with Vite

### ISSUE THREAD

**Issue by daniele-zurico** [Capgemini/dcx-react-library#599]
CRA is deprecated and most of the projects are based on Vite. Please remove CRA from the example folder and migrate the solution to Vite solution

Link to Vite: https://vitejs.dev/guide/
Old version for comparison: https://create-react-app.dev/docs/getting-started/

**Comment by alexwbbr** [comment]
https://github.com/Capgemini/dcx-react-library/pull/603
