### ISSUE TITLE
Heading does no apply the css correctly

### ISSUE THREAD

**Issue by capJuan** [Capgemini/dcx-react-library#610]
**Describe the bug**
Having 2 headings , one level 1 and another level 4 , the colour css setting for level 1 is also apply to the heading level 4

**To Reproduce**
1. create a page with 2 headings  one level 1 and one level 4 
2. set css for both using tokens  --dcx-color-text-heading-level_1 and --dcx-color-text-heading-level_4 different colours
3. render the page ( level 1 colour is applied to both headdings ( ignoring the level 4 color csss)

**Expected behavior**
the heading should render using different colour as css 

**Screenshots**

**Desktop (please complete the following information):**
![Screenshot 2024-03-22 at 12 19 59](https://github.com/Capgemini/dcx-react-library/assets/26276923/4e56bc28-ed8d-4cfc-93c8-5256f2dfda57)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/620
