### ISSUE TITLE
Form input props wrong typing and expose input ref

### ISSUE THREAD

**Issue by jgonza16** [Capgemini/dcx-react-library#626]
**Describe the bug**
when you want use form input with useForm library for example no work because this library need input ref to handle inputs and if you use formInputProps typescript lint throw errors an we has css problems with label because value prop is not handle with state and no update to `dcx-form-input--filled`. The placeholder has't tokens to change color anda font-sizes

**To Reproduce**
1. try use formInput handle ref way or spread React.HTMLAttributes<HTMLInputElement> into inputProps

**Expected behavior**
No linter errros and use input native ref

**Screenshots**

**Desktop (please complete the following information):**
<img width="1062" alt="image" src="https://github.com/Capgemini/dcx-react-library/assets/93665374/5117f8f6-6a09-426b-8d5e-ae0fe9fe3a1f">

![image](https://github.com/Capgemini/dcx-react-library/assets/93665374/64aa1e80-93c4-4e02-9f7d-433e6ab1d450)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/627
