### ISSUE TITLE
FormInput: An aria attribute has been given an invalid value

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#631]
**Describe the bug**
Component: FormInput

An invalid aria attribute value was found through running an accessibility test. This instance
can be found with a `<div>` element being provided with a ‘role’ attribute and an ‘error’
value.

**Expected behavior**
Ensure that the appropriate roles are used to allow all information to be adequately
conveyed and announced to users of screen reading assistive technologies. The role should
not be set to ‘error’.
Consider changing these to have a role of ‘alert’ if the intention is to have them announce to
screen reader users.

Please conditionally add the element when an error message is to be displayed

**Screenshots**
<img width="945" alt="Screenshot 2024-04-16 at 11 28 58" src="https://github.com/Capgemini/dcx-react-library/assets/11960286/0cecaa2d-4e1a-4eca-84ef-9cf21fd570e6">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/632
