### ISSUE TITLE
<Details /> contains a default TabIndex = 0

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#640]
**Describe the bug**
The Details component contains a default tabIndex of 0, which is not always desirable.

**To Reproduce**
Render the `<Details />` component

**Expected behavior**
Please provide a way to `null` the tabIndex such that it does not render in the DOM if not required

**Screenshots**
![image](https://github.com/Capgemini/dcx-react-library/assets/11960286/799105ab-c70e-46b2-9fd3-fce2a2feb095)

**Comment by daniele-zurico** [comment]
closed by #641
