### ISSUE TITLE
Update the autocomplete so that screen readers behave properly

### ISSUE THREAD

**Issue by alexwbbr** [Capgemini/dcx-react-library#644]
**Describe the bug**
When a screen reader gets to the autocomplete it will read out the hidden accessibility text first before the descriptive label. This needs to be changed so that the label and hint for the autocomplete is read first before the hidden accessibility text.

The autocomplete should also close the options list on blur as that is causing some confusion with screen readers which can cause text to be read out of order again.

All of the examples in the government design accessible autocomplete close on blur so I think we should follow suit.
https://alphagov.github.io/accessible-autocomplete/examples/

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/645
