### ISSUE TITLE
Accessibility: Button component is adding label as aria-label

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#663]
**Describe the bug**
When an aria label has not been provided Button component is adding label as aria-label, which conflicts with the visible label.

**Expected behavior**
```tsx
export const Button = ({
  label,
  ...
  ariaLabel = `${label}`, // this is not required
  ```
  
  ```html
<button type="submit" aria-label="THIS IS NOT REQUIRED IF NOT PROVIDED" class="dcx-button" id="some-id">
Visible Label<span class="visually-hidden">Hidden Text</span>
</button>
```
  ** Required Action **
  - [ ] remove the default addition of `label` to `aria-label`

**Comment by daniele-zurico** [comment]
closed by #664
