### ISSUE TITLE
Spinner Component

### ISSUE THREAD

**Issue by daiseybtw** [Capgemini/dcx-react-library#691]
**Describe the solution you'd like**
A spinner to indicate the application is currently busy.

Given I am submitting a form
And I use the DCX React Library,
Then I should be able to import a spinning loading icon to show visual feedback that the application is doing something.

Technical Details
The spinner should be customisable with classes, or props controlling speed, colour etc.
See the following link from MUi for an example of it
https://mui.com/material-ui/react-progress/

Set up:

```
git checkout release/1.1.0
git pull
git checkout -b 'feature/spinner'
```

**Comment by daniele-zurico** [comment]
closed by https://github.com/Capgemini/dcx-react-library/pull/690
